# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    List as typing___List,
    Mapping as typing___Mapping,
    MutableMapping as typing___MutableMapping,
    Optional as typing___Optional,
    Text as typing___Text,
    Tuple as typing___Tuple,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Span(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    class Kind(int):
        DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
        @classmethod
        def Name(cls, number: int) -> str: ...
        @classmethod
        def Value(cls, name: str) -> Span.Kind: ...
        @classmethod
        def keys(cls) -> typing___List[str]: ...
        @classmethod
        def values(cls) -> typing___List[Span.Kind]: ...
        @classmethod
        def items(cls) -> typing___List[typing___Tuple[str, Span.Kind]]: ...
        SPAN_KIND_UNSPECIFIED = typing___cast(Span.Kind, 0)
        CLIENT = typing___cast(Span.Kind, 1)
        SERVER = typing___cast(Span.Kind, 2)
        PRODUCER = typing___cast(Span.Kind, 3)
        CONSUMER = typing___cast(Span.Kind, 4)
    SPAN_KIND_UNSPECIFIED = typing___cast(Span.Kind, 0)
    CLIENT = typing___cast(Span.Kind, 1)
    SERVER = typing___cast(Span.Kind, 2)
    PRODUCER = typing___cast(Span.Kind, 3)
    CONSUMER = typing___cast(Span.Kind, 4)

    class TagsEntry(google___protobuf___message___Message):
        DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
        key = ... # type: typing___Text
        value = ... # type: typing___Text

        def __init__(self,
            *,
            key : typing___Optional[typing___Text] = None,
            value : typing___Optional[typing___Text] = None,
            ) -> None: ...
        @classmethod
        def FromString(cls, s: bytes) -> Span.TagsEntry: ...
        def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
        if sys.version_info >= (3,):
            def ClearField(self, field_name: typing_extensions___Literal[u"key",u"value"]) -> None: ...
        else:
            def ClearField(self, field_name: typing_extensions___Literal[u"key",b"key",u"value",b"value"]) -> None: ...

    trace_id = ... # type: bytes
    parent_id = ... # type: bytes
    id = ... # type: bytes
    kind = ... # type: Span.Kind
    name = ... # type: typing___Text
    timestamp = ... # type: int
    duration = ... # type: int
    debug = ... # type: bool
    shared = ... # type: bool

    @property
    def local_endpoint(self) -> Endpoint: ...

    @property
    def remote_endpoint(self) -> Endpoint: ...

    @property
    def annotations(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Annotation]: ...

    @property
    def tags(self) -> typing___MutableMapping[typing___Text, typing___Text]: ...

    def __init__(self,
        *,
        trace_id : typing___Optional[bytes] = None,
        parent_id : typing___Optional[bytes] = None,
        id : typing___Optional[bytes] = None,
        kind : typing___Optional[Span.Kind] = None,
        name : typing___Optional[typing___Text] = None,
        timestamp : typing___Optional[int] = None,
        duration : typing___Optional[int] = None,
        local_endpoint : typing___Optional[Endpoint] = None,
        remote_endpoint : typing___Optional[Endpoint] = None,
        annotations : typing___Optional[typing___Iterable[Annotation]] = None,
        tags : typing___Optional[typing___Mapping[typing___Text, typing___Text]] = None,
        debug : typing___Optional[bool] = None,
        shared : typing___Optional[bool] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Span: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"local_endpoint",u"remote_endpoint"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"annotations",u"debug",u"duration",u"id",u"kind",u"local_endpoint",u"name",u"parent_id",u"remote_endpoint",u"shared",u"tags",u"timestamp",u"trace_id"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"local_endpoint",b"local_endpoint",u"remote_endpoint",b"remote_endpoint"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"annotations",b"annotations",u"debug",b"debug",u"duration",b"duration",u"id",b"id",u"kind",b"kind",u"local_endpoint",b"local_endpoint",u"name",b"name",u"parent_id",b"parent_id",u"remote_endpoint",b"remote_endpoint",u"shared",b"shared",u"tags",b"tags",u"timestamp",b"timestamp",u"trace_id",b"trace_id"]) -> None: ...

class Endpoint(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    service_name = ... # type: typing___Text
    ipv4 = ... # type: bytes
    ipv6 = ... # type: bytes
    port = ... # type: int

    def __init__(self,
        *,
        service_name : typing___Optional[typing___Text] = None,
        ipv4 : typing___Optional[bytes] = None,
        ipv6 : typing___Optional[bytes] = None,
        port : typing___Optional[int] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Endpoint: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"ipv4",u"ipv6",u"port",u"service_name"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"ipv4",b"ipv4",u"ipv6",b"ipv6",u"port",b"port",u"service_name",b"service_name"]) -> None: ...

class Annotation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    timestamp = ... # type: int
    value = ... # type: typing___Text

    def __init__(self,
        *,
        timestamp : typing___Optional[int] = None,
        value : typing___Optional[typing___Text] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Annotation: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"timestamp",u"value"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"timestamp",b"timestamp",u"value",b"value"]) -> None: ...

class ListOfSpans(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    @property
    def spans(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[Span]: ...

    def __init__(self,
        *,
        spans : typing___Optional[typing___Iterable[Span]] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ListOfSpans: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def ClearField(self, field_name: typing_extensions___Literal[u"spans"]) -> None: ...
    else:
        def ClearField(self, field_name: typing_extensions___Literal[u"spans",b"spans"]) -> None: ...

class ReportResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...

    def __init__(self,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> ReportResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
